[config]
label = "My Project"
# Relative to this files location
root_path = "../testProject"
# Will be split into string array for command ["go", "run", "main.go"]
exec_command = "go run main.go"

# debug | info | warn | error | fatal
log_level = "info"

[color_scheme]
debug = "#87CEEB"  # Sky Blue
info = "#98FB98"   # Pale Green
warn = "#FFD700"   # Gold
error = "#FFA07A"  # Light Salmon
fatal = "#FF6347"  # Tomato

[config.ignore]
dir = [".git", "node_modules"]
file = [".DS_Store", ".gitignore", ".gitkeep", "newfile.go"]
extension = [".db", ".sqlite"]
