[config]
# Just used in the TUI not required
label = "My Project"
# Relative to this files location
root_path = "../testProject"
# Runs prior to the exec command starting
pre_exec = ""
exec_command = "go build main.go"
# Runs when a file reload is triggered after killing the previous process
post_exec = ""
# debug | info | warn | error | fatal
# Defaults to Info if not provided
log_level = "info" 

# Sets what files the watcher should ignore
[config.ignore]
# Directories to ignore
dir = [".git", "node_modules"]
# Files to ignore
file = [".DS_Store", ".gitignore", ".gitkeep", "newfile.go"]
# File extensions to ignore
extension = [".db", ".sqlite"]

# Sets logging color scheme
[color_scheme]
debug = "#87CEEB"  # Sky Blue
info = "#98FB98"   # Pale Green
warn = "#FFD700"   # Gold
error = "#FFA07A"  # Light Salmon
fatal = "#FF6347"  # Tomato

